### ISSUE TITLE
TikaOnDotNet getting error when calling TikaOnDot from another DLL.

### ISSUE THREAD

**Issue by jjoravec** [KevM/tikaondotnet#15]
I came across your TikaOnDotNet and it works great for me if I call it from my windows application, but when I make the same call to extract from another DLL it fails on the CreateInstance.  

Basically the path is:   Application ---calls--> Custom DLL ---calls--> TikaOnDotnet

The error I get is 

"Provider com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl not found"

It is thrown on the following line of code 

TransformerFactory factory = TransformerFactory.newInstance();

Any thoughts or suggestions on getting the TikaOnDotNet to work when called from an intermediate DLL.

Thanks

Joe

**Comment by KevM** [comment]
@JeffCt Thanks for the info dump.

**Comment by joekrill** [comment]
Although this issue has been closed, I just wanted to throw in my experience with the same problem, in case it helps anyone else seeing the same error, which actually wasn't really a problem with the class loader, but of missing DLLs.

In my particular case, I had a web application that referenced a class library project, which in turn referenced TikaOnDotnet:

    Web Application --> My Class Library --> TikaOnDotNet

When I deployed my web application, I was seeing the same exact error mentioned in the original issue. It turned out that not all of the IKVM DLLs were being deployed with my web application -- even though my class library referenced them, and "Copy Local" was set to true. It seems this is because they were not *directly* referenced. 

In particular, it was `IKVM.OpenJDK.XML.Transform.dll` that was missing and causing the problem. But I also noticed `IKVM.OpenJDK.Tools.dll` and `IKVM.OpenJDK.XML.WebServices.dll` were missing, too. 

I was able to get them to be deployed by explicitly referencing a class defined in those DLLs. So I have a static constructor that includes this code:

    var t = typeof(com.sun.codemodel.@internal.ClassType); // IKVM.OpenJDK.Tools
    t = typeof(com.sun.org.apache.xalan.@internal.xsltc.trax.TransformerFactoryImpl); // IKVM.OpenJDK.XML.Transform
    t = typeof(com.sun.org.glassfish.external.amx.AMX); // IKVM.OpenJDK.XML.WebServices

I'm still not convinced that's the *best* solution to the problem, but I wasn't able to find a better workaround.

**Comment by dsherret** [comment]
@joekrill interesting. I was getting this error when I was trying this library out in some unit tests and adding a dummy private function with that code (`var t =  typeof(....etc...`) fixed it for me even though those dlls are set with copy local to true as well...

**Comment by KevM** [comment]
@joekrill sounds like we need to document this somewhere better than a GitHub issue. Anyone want to take a stab at a markdown guide to referencing TikeOnDotNet properly?

**Comment by bergmeister** [comment]
@joekrill , Thanks, I had the same issue because I wanted to wrap Tika in a class library of its own and your quick-hack worked for me as well. :-)
@KevM Maybe instead of documenting it, what about catching the specific exception and re-throwing an exception with a good error text that could e.g. include useful links? I was actually quite close to giving up and trying a different library after about half an hour...

**Comment by KevM** [comment]
@bergmeister That sounds like a good idea. Can you put forward some code as a proof of concept? Maybe implement it as a breaking test?

**Comment by LeeBear35** [comment]
I have a test harness to confirm certain document extracts that calls the TikaOnDotNet.TextExtractionOCR.TextExtractor().Extract and it started to fail, when I checked the steps above like the:
var t = typeof(com.sun.codemodel.@internal.ClassType); // IKVM.OpenJDK.Tools 
and Stepped through using Unit Test Debug, the call to set t was optimized out in the release version I was testing, and caused the tests to fail.

My solution which worked regardless of release or debug testing was to create entries that would not be optimized out using private static entries, hope this helps:

[TestClass]
  public class Tika_UnitTests
  {
    private static Type IKVM_OpenJDK_Tools = typeof(com.sun.codemodel.@internal.ClassType);
    private static Type IKVM_OpenJDK_XML_Transform = typeof(com.sun.org.apache.xalan.@internal.xsltc.trax.TransformerFactoryImpl);
    private static Type IKVM_OpenJDK_XML_WebServices = typeof(com.sun.org.glassfish.external.amx.AMX);
